global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'envoy-canary'
    static_configs:
      - targets: ['envoy-canary:9901']
    metrics_path: /stats/prometheus

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
