services:
  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: phoenix-soc
    ports:
      - "6006:6006"   # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - PHOENIX_WORKING_DIR=/phoenix

  prometheus:
    image: prom/prometheus
    container_name: prometheus-soc
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana-soc
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
